<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>JAHTTPClient.Sample</RootNamespace>
    <AssemblyName>JAHTTPClient.Sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JAHTTPClient\JAHTTPClient.csproj" />
  </ItemGroup>

</Project>
